---
# These tasks install nginx web server with unicorn and all dependent modules.

- name: Add group nginx
  group: name=web state=present

- name: Add user nginx, and forbid this nginx user to login shell
  user: name=nginx  shell=/sbin/nologin group=web

- name: Install the latest release repo for nginx
  command: rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  ignore_errors: yes

- name: Install nginx git gcc and ruby etc. It costs about 5 to 10 minusts
  yum: name={{ item }} state=present
  with_items:
   - libcurl-devel
   - ruby
   - ruby-devel
   - apr-devel
   - apr-util-devel
   - rubygems
   - zlib
   - zlib-devel
   - openssl-devel
   - git
   - gcc
   - gcc-c++
   - nginx
   - libselinux-python

- name: Install Development Tools package group
  yum: name="@Development tools" state=present
 
- name: gem install bundle and unicorn
  gem: name={{ item }} state=latest user_install=no
  with_items:
   - bundle 
   - unicorn
